#!/usr/bin/env python
import gi
import sys

gi.require_version('Playerctl', '1.0')
from gi.repository import Playerctl, GLib

icons = {
    "play": "",
    "pause": "",
    "music": "",
    }

player_name=sys.argv[1]
timeout = 2


def player_is_running(player_name=player_name):
    return Playerctl.Player(player_name=player_name).props.metadata is not None

def handler(signum, frame):
    raise TimeoutError

def on_metadata(player,e=None):
    e = player.props.metadata if e is None else e
    if player_is_running(player_name):
        artist = e['xesam:artist'][0]
        title = e['xesam:title']
        icon = icons['play'] if player.props.status == 'Playing' else icons['pause']
        print(f'{icons["music"]}{artist} - {title} {icon}')
    sys.exit(0)

if not player_is_running(player_name):
    sys.exit(1)


player = Playerctl.Player(player_name=player_name)
player.on('metadata', on_metadata)

main = GLib.MainLoop()
GLib.timeout_add_seconds(timeout,lambda: on_metadata(player))
main.run()
